# Generated by Django 3.2.16 on 2023-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_auto_20230523_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
