# Generated by Django 3.2.16 on 2023-05-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cname',
        ),
    ]
