# Generated by Django 3.2.16 on 2023-05-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0006_rename_user_cartitem_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cname',
        ),
    ]
